version: '3.8'

services:
  sol-trading-bot:
    container_name: sol_trader
    build:
      context: .
      dockerfile: Dockerfile
    
    # Restart policy - always restart if crashed
    restart: unless-stopped
    
    # Environment variables from .env file
    env_file:
      - .env
    
    # Volume for logs (persist logs on host)
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    
    # Resource limits (prevent bot from using too much)
    deploy:
      resources:
        limits:
          cpus: '0.5'      # Max 50% of 1 CPU
          memory: 512M     # Max 512MB RAM
        reservations:
          cpus: '0.25'     # Reserve 25% CPU
          memory: 256M     # Reserve 256MB RAM
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"    # Max log file size
        max-file: "3"      # Keep 3 rotated logs
    
    # Network mode
    network_mode: bridge
    
    # Labels for organization
    labels:
      - "app=sol-trading-bot"
      - "version=1.0"
      - "environment=production"

# Optional: Add a monitoring service (Prometheus/Grafana)
# Uncomment to enable monitoring
#
#  prometheus:
#    image: prom/prometheus:latest
#    container_name: sol_prometheus
#    restart: unless-stopped
#    volumes:
#      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
#      - prometheus_data:/prometheus
#    ports:
#      - "9090:9090"
#    command:
#      - '--config.file=/etc/prometheus/prometheus.yml'
#
#volumes:
#  prometheus_data:
